const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');

function read(filePath) {
  return fs.readFileSync(path.join(root, filePath), 'utf8');
}

function write(filePath, content) {
  fs.writeFileSync(path.join(root, filePath), content, 'utf8');
}

function transformModule(source) {
  return source
    .replace(/^import\s+.*?;\r?\n/gm, '')
    .replace(/^export\s+const\s+/gm, 'const ')
    .replace(/^export\s+async\s+function\s+/gm, 'async function ')
    .replace(/^export\s+function\s+/gm, 'function ')
    .trim();
}

const config = transformModule(read('src/config.js'));
const simulation = transformModule(read('src/simulation.js'));
const rendering = transformModule(read('src/rendering.js'));
const ui = transformModule(read('src/ui.js'));

const main = read('game.js')
  .replace(/^import\s+[\s\S]*?from '\.\/src\/ui\.js';\r?\n/m, '')
  .trim();

const runtime = [
  '/* Generated by tools/build-runtime.js. Edit source files instead. */',
  config,
  '',
  simulation,
  '',
  rendering,
  '',
  ui,
  '',
  main,
  '',
].join('\n');

write('game.runtime.js', runtime);
